version: '3.7'

services:
  node-uni-1-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=nodeuser1
      - POSTGRES_PASSWORD=nodepass1
      - POSTGRES_DB=edublock
    ports:
      - 5434:5432
  node-uni-2-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=nodeuser2
      - POSTGRES_PASSWORD=nodepass2
      - POSTGRES_DB=edublock
    ports:
      - 5435:5432
  node-uni-3-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=nodeuser3
      - POSTGRES_PASSWORD=nodepass3
      - POSTGRES_DB=edublock
    ports:
      - 5436:5432
  node-uni-4-db:
    image: "postgres"
    environment:
      - POSTGRES_USER=nodeuser4
      - POSTGRES_PASSWORD=nodepass4
      - POSTGRES_DB=edublock
    ports:
      - 5437:5432
